"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { Card } from "@/components/ui/card";
import { analyzeTrades } from "@/features/analytics/engine";
import { tradeRepository } from "@/features/trades/storage";
import type { Trade } from "@/features/trades/types";
export function TradingDashboard(){const[trades,setTrades]=useState<Trade[]>([]);useEffect(()=>setTrades(tradeRepository.list()),[]);const s=useMemo(()=>analyzeTrades(trades),[trades]);const recent=[...trades].sort((a,b)=>new Date(b.openedAt).getTime()-new Date(a.openedAt).getTime()).slice(0,5);const closed=s.closedTrades;return <>
<section className="dashboard-command"><div><p className="eyebrow">TRADING OVERVIEW</p><h2>Your trading, in one view.</h2><p>Review recorded activity first, then move from results to the patterns behind them.</p></div><div className="dashboard-command__actions"><Link className="tv-button" href="/workspace/calendar">Trading Calendar</Link><Link className="tv-button tv-button--primary" href="/workspace/journal">+ Add Trade</Link></div></section>
<section className="metric-grid"><Metric label="Net P&L" value={closed?money(s.netPnl):"—"} tone={closed?s.netPnl:undefined}/><Metric label="Win Rate" value={pct(s.winRate)}/><Metric label="Profit Factor" value={num(s.profitFactor)}/><Metric label="Avg. Realized R" value={rr(s.averageRealizedR)}/></section>
<section className="dashboard-context"><span><b>{trades.length}</b> recorded trades</span><span><b>{closed}</b> closed with P&amp;L</span><span><b>{Math.max(0,trades.length-closed)}</b> open / incomplete</span><small>Performance metrics use closed trades with recorded Net P&amp;L only.</small></section>
<section className="dashboard-grid"><Card className="dashboard-panel"><div className="panel-heading"><div><p className="eyebrow">RECENT ACTIVITY</p><h2>Latest Trades</h2></div><Link href="/workspace/journal">Open Journal →</Link></div>{recent.length?<div className="recent-trades">{recent.map(t=><div key={t.id}><span><strong>{t.symbol}</strong><small>{new Date(t.openedAt).toLocaleDateString()} · {t.side}{t.strategy?` · ${t.strategy}`:""}</small></span><b className={pnlTone(t.netPnl)}>{moneyOptional(t.netPnl)}</b></div>)}</div>:<Empty text="Add your first trade to start building the dashboard." href="/workspace/journal"/>}</Card>
<Card className="dashboard-panel dashboard-intelligence"><div className="panel-heading"><div><p className="eyebrow">TRADOVIA INTELLIGENCE</p><h2>Performance Review</h2></div><Link href="/workspace/analytics">Analytics →</Link></div>{closed?<div className="insight-stack"><div><span>RESULT · STRONGEST EDGE</span><strong>{s.bestStrategy?`${s.bestStrategy.name} · ${money(s.bestStrategy.netPnl)}`:"Add strategy labels to reveal patterns"}</strong></div><div><span>WHY · BIGGEST LEAK</span><strong>{s.worstStrategy&&s.worstStrategy.netPnl<0?`${s.worstStrategy.name} · ${money(s.worstStrategy.netPnl)}`:"No negative strategy pattern identified yet"}</strong></div><div><span>ACTION · REVIEW NEXT</span><strong>Inspect the underlying trades before changing your process.</strong></div></div>:<Empty text={trades.length?"Record Net P&L on closed trades to unlock realized performance review.":"Intelligence appears after your journal contains closed trade history."} href="/workspace/journal"/>}</Card></section>
<section className="dashboard-shortcuts"><Link href="/workspace/calendar"><span>REVIEW</span><strong>Trading Calendar</strong><small>Day · Week · Month · Year</small></Link><Link href="/workspace/playbook"><span>PROCESS</span><strong>Playbook</strong><small>Keep setup and execution rules visible.</small></Link><Link href="/workspace/goals"><span>DISCIPLINE</span><strong>Goals &amp; Rules</strong><small>Weekly · Monthly · Yearly</small></Link><Link href="/workspace/risk"><span>PLAN</span><strong>Risk Calculator</strong><small>Simple R:R and supported risk math.</small></Link></section>
</>}
function Metric({label,value,tone}:{label:string;value:string;tone?:number}){return <Card className="metric-card"><span>{label}</span><strong className={tone===undefined?"":tone>0?"positive":tone<0?"negative":""}>{value}</strong><small>Closed trades · recorded P&amp;L</small></Card>}
function Empty({text,href}:{text:string;href:string}){return <div className="dashboard-empty"><p>{text}</p><Link className="tv-button" href={href}>Open Journal</Link></div>}
function money(v:number){return `${v<0?"-":""}$${Math.abs(v).toFixed(2)}`}function moneyOptional(v?:number){return v===undefined||!Number.isFinite(v)?"—":money(v)}function pnlTone(v?:number){return v===undefined||!Number.isFinite(v)?"":v>0?"positive":v<0?"negative":""}function pct(v?:number){return v===undefined?"—":`${v.toFixed(1)}%`}function num(v?:number){return v===undefined?"—":v.toFixed(2)}function rr(v?:number){return v===undefined?"—":`${v.toFixed(2)}R`}
