"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { tradeRepository } from "./storage";
import type { Trade, TradeDraft, TradeSide } from "./types";
import { enrichTradeDraft } from "./calculations";

const emptyDraft: TradeDraft = { symbol: "XAUUSD", side: "Long", openedAt: "", entry: 0, stopLoss: 0 };

export function TradeJournal() {
  const [trades, setTrades] = useState<Trade[]>([]), [draft, setDraft] = useState<TradeDraft>(emptyDraft);
  const [formOpen, setFormOpen] = useState(false), [selected, setSelected] = useState<Trade | null>(null), [editingId, setEditingId] = useState<string | null>(null), [query, setQuery] = useState("");
  useEffect(() => setTrades(tradeRepository.list()), []);
  const preview = useMemo(() => enrichTradeDraft(draft), [draft]);
  const filtered = trades.filter(t => `${t.symbol} ${t.strategy ?? ""} ${t.setup ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const refresh = () => setTrades(tradeRepository.list());
  const startAdd = () => { setEditingId(null); setDraft(emptyDraft); setFormOpen(true); };
  const startEdit = (trade: Trade) => { setSelected(null); setEditingId(trade.id); setDraft(toDraft(trade)); setFormOpen(true); };

  function submit(event: FormEvent) {
    event.preventDefault(); if (!draft.symbol.trim() || !draft.openedAt || !draft.entry || !draft.stopLoss) return;
    editingId ? tradeRepository.update(editingId, draft) : tradeRepository.create(draft);
    refresh(); setDraft(emptyDraft); setEditingId(null); setFormOpen(false);
  }
  function remove(trade: Trade) { if (!window.confirm(`Delete ${trade.symbol} trade? This cannot be undone.`)) return; tradeRepository.remove(trade.id); setSelected(null); refresh(); }

  return <>
    <div className="journal-toolbar"><input className="tv-field" placeholder="Search symbol, strategy or setup" value={query} onChange={e=>setQuery(e.target.value)}/><button className="tv-button tv-button--primary" onClick={startAdd}>+ Add Trade</button></div>
    <div className="journal-table-wrap"><table className="journal-table"><thead><tr><th>Date / Time</th><th>Asset</th><th>Side</th><th>Entry</th><th>Initial Risk</th><th>Planned R:R</th><th>Net P&L</th><th>Realized R</th></tr></thead><tbody>{filtered.length ? filtered.map(t=><tr key={t.id} className="trade-row" onClick={()=>setSelected(t)}><td>{date(t.openedAt)}</td><td><strong>{t.symbol}</strong></td><td>{t.side}</td><td>{t.entry}</td><td>{money(t.initialRisk)}</td><td>{ratio(t.plannedRR)}</td><td className={(t.netPnl??0)>=0?"positive":"negative"}>{money(t.netPnl)}</td><td>{ratio(t.realizedR)}</td></tr>) : <tr><td colSpan={8}><div className="empty-state"><strong>No trades yet</strong><span>Add your first trade to start building your trading history.</span><button className="tv-button" onClick={startAdd}>Add Trade</button></div></td></tr>}</tbody></table></div>
    {selected && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><article className="trade-modal detail-modal"><div className="modal-heading"><div><p className="eyebrow">TRADE DETAIL</p><h2>{selected.symbol} · {selected.side}</h2><p className="detail-date">{date(selected.openedAt)}</p></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></div><div className="detail-grid"><Detail label="Entry" value={String(selected.entry)}/><Detail label="Initial SL" value={String(selected.stopLoss)}/><Detail label="Take Profit" value={value(selected.takeProfit)}/><Detail label="Exit" value={value(selected.exit)}/><Detail label="Initial Risk" value={money(selected.initialRisk)}/><Detail label="Planned R:R" value={ratio(selected.plannedRR)}/><Detail label="Net P&L" value={money(selected.netPnl)}/><Detail label="Realized R" value={ratio(selected.realizedR)}/><Detail label="Strategy" value={selected.strategy||"—"}/><Detail label="Setup" value={selected.setup||"—"}/></div>{selected.notes&&<div className="detail-notes"><span>Notes</span><p>{selected.notes}</p></div>}<div className="modal-actions detail-actions"><button className="tv-button danger-button" onClick={()=>remove(selected)}>Delete</button><span/><button className="tv-button" onClick={()=>setSelected(null)}>Close</button><button className="tv-button tv-button--primary" onClick={()=>startEdit(selected)}>Edit Trade</button></div></article></div>}
    {formOpen && <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setFormOpen(false)}}><form className="trade-modal" onSubmit={submit}><div className="modal-heading"><div><p className="eyebrow">JOURNAL</p><h2>{editingId?"Edit Trade":"Add Trade"}</h2></div><button type="button" className="icon-button" onClick={()=>setFormOpen(false)}>×</button></div><div className="trade-form-grid"><Field label="Asset"><input className="tv-field" value={draft.symbol} onChange={e=>setDraft({...draft,symbol:e.target.value.toUpperCase()})}/></Field><Field label="Side"><select className="tv-field" value={draft.side} onChange={e=>setDraft({...draft,side:e.target.value as TradeSide})}><option>Long</option><option>Short</option></select></Field><Field label="Date & Time"><input className="tv-field" type="datetime-local" value={draft.openedAt} onChange={e=>setDraft({...draft,openedAt:e.target.value})}/></Field><Field label="Lot Size"><input className="tv-field" type="number" step="any" value={draft.lotSize??""} onChange={e=>setDraft({...draft,lotSize:num(e.target.value)})}/></Field><Field label="Entry"><input className="tv-field" type="number" step="any" value={draft.entry||""} onChange={e=>setDraft({...draft,entry:Number(e.target.value)})}/></Field><Field label="Initial SL"><input className="tv-field" type="number" step="any" value={draft.stopLoss||""} onChange={e=>setDraft({...draft,stopLoss:Number(e.target.value)})}/></Field><Field label="Take Profit"><input className="tv-field" type="number" step="any" value={draft.takeProfit??""} onChange={e=>setDraft({...draft,takeProfit:num(e.target.value)})}/></Field><Field label="Net P&L"><input className="tv-field" type="number" step="any" value={draft.netPnl??""} onChange={e=>setDraft({...draft,netPnl:num(e.target.value)})}/></Field><Field label="Strategy"><input className="tv-field" value={draft.strategy??""} onChange={e=>setDraft({...draft,strategy:e.target.value})}/></Field><Field label="Setup"><input className="tv-field" value={draft.setup??""} onChange={e=>setDraft({...draft,setup:e.target.value})}/></Field></div><div className="risk-summary"><Detail label="Planned R:R" value={ratio(preview.plannedRR)}/><Detail label="Initial Risk" value={money(preview.initialRisk)}/><Detail label="Realized R" value={ratio(preview.realizedR)}/></div><label className="notes-label">Notes<textarea className="tv-field" rows={4} value={draft.notes??""} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="modal-actions"><button type="button" className="tv-button" onClick={()=>setFormOpen(false)}>Cancel</button><button className="tv-button tv-button--primary">{editingId?"Save Changes":"Save Trade"}</button></div></form></div>}
  </>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label>{label}{children}</label>}
function Detail({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function toDraft(t:Trade):TradeDraft{const {id:_,plannedRR:__,realizedR:___,...draft}=t;return draft}
function num(v:string){return v===""?undefined:Number(v)} function value(v?:number){return v===undefined?"—":String(v)}
function money(v?:number){return v===undefined||!Number.isFinite(v)?"—":`${v<0?"-":""}$${Math.abs(v).toFixed(2)}`} function ratio(v?:number){return v===undefined||!Number.isFinite(v)?"—":`${v.toFixed(2)}R`} function date(v:string){const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString()}
