"use client";
import { useEffect,useMemo,useState } from "react";
import { tradeRepository } from "@/features/trades/storage";
import type { Trade } from "@/features/trades/types";
import { analyzeTrades,groupByStrategy,groupBySymbol } from "./engine";
export function AnalyticsDashboard(){const [trades,setTrades]=useState<Trade[]>([]);useEffect(()=>setTrades(tradeRepository.list()),[]);const s=useMemo(()=>analyzeTrades(trades),[trades]),symbols=useMemo(()=>groupBySymbol(trades),[trades]),strategies=useMemo(()=>groupByStrategy(trades),[trades]);return <>
<div className="analytics-metrics"><Metric label="Net P&L" value={money(s.netPnl)} tone={s.netPnl}/><Metric label="Win Rate" value={pct(s.winRate)}/><Metric label="Profit Factor" value={num(s.profitFactor)}/><Metric label="Avg. Realized R" value={r(s.averageRealizedR)}/><Metric label="Trades" value={String(s.totalTrades)}/><Metric label="Avg. Win" value={moneyOpt(s.averageWin)}/><Metric label="Avg. Loss" value={moneyOpt(s.averageLoss)}/><Metric label="W / L" value={`${s.wins} / ${s.losses}`}/></div>
<div className="analytics-grid"><section className="tv-card analytics-panel"><div className="panel-heading"><div><p className="eyebrow">PERFORMANCE</p><strong>By Asset</strong></div></div><GroupTable rows={symbols}/></section><section className="tv-card analytics-panel"><div className="panel-heading"><div><p className="eyebrow">EXECUTION</p><strong>By Strategy</strong></div></div><GroupTable rows={strategies}/></section></div>
<section className="tv-card intelligence-panel"><p className="eyebrow">TRADOVIA INTELLIGENCE</p>{trades.length?<div className="intelligence-results"><Insight label="Result" text={s.bestStrategy?`${s.bestStrategy.name} is currently your strongest strategy by realized net P&L (${money(s.bestStrategy.netPnl)}).`:"Not enough strategy data yet."}/><Insight label="Why" text={s.bestStrategy?`Based on ${s.bestStrategy.trades} recorded trade${s.bestStrategy.trades===1?"":"s"} with ${pct(s.bestStrategy.winRate)} win rate. This is descriptive, not a trading signal.`:"Add strategy labels to trades to make this comparison useful."}/><Insight label="Action" text="Review the underlying trades before changing your process. Look for repeatable execution patterns and rule adherence."/></div>:<div className="analytics-empty">Add trades to generate performance patterns from your own journal data.</div>}</section>
</>}
function Metric({label,value,tone}:{label:string;value:string;tone?:number}){return <div className="tv-card analytics-metric"><span>{label}</span><strong className={tone===undefined?"":tone>=0?"positive":"negative"}>{value}</strong></div>}
function GroupTable({rows}:{rows:{name:string;trades:number;netPnl:number;winRate:number}[]}){return rows.length?<div className="analytics-table">{rows.slice(0,8).map(x=><div key={x.name}><strong>{x.name}</strong><span>{x.trades} trades</span><span>{pct(x.winRate)}</span><b className={x.netPnl>=0?"positive":"negative"}>{money(x.netPnl)}</b></div>)}</div>:<div className="analytics-empty">No trade data yet.</div>}
function Insight({label,text}:{label:string;text:string}){return <div><span>{label}</span><p>{text}</p></div>}
function money(v:number){return `${v<0?"-":""}$${Math.abs(v).toFixed(2)}`} function moneyOpt(v?:number){return v===undefined?"—":money(v)} function pct(v?:number){return v===undefined?"—":`${v.toFixed(1)}%`} function num(v?:number){return v===undefined?"—":v.toFixed(2)} function r(v?:number){return v===undefined?"—":`${v.toFixed(2)}R`}
