import Link from "next/link";
import { TradoviaLogo } from "@/components/brand/tradovia-logo";
import { Card } from "@/components/ui/card";

const workflow = ["Trades", "Data", "Patterns", "Insights", "Decisions", "Improvement"];
const productAreas = [
  ["Trading Journal", "Capture the trade, context, screenshots and execution without turning journaling into admin work."],
  ["Trading Calendar", "See trading activity and realized P&L by day, week, month and year."],
  ["Performance Intelligence", "Turn trade history into understandable patterns, leaks and areas worth reviewing."],
];
const environment = [
  ["TradingView", "Keep chart review close to the journal workflow."],
  ["Economic Calendar", "A dedicated place for macro-event context without pretending unverified data is live."],
  ["Market News", "Market context remains separate from your personal performance data."],
  ["Risk Calculator", "Plan R:R and supported risk calculations without hiding broker-specific assumptions."],
];
const trust = ["Your journal is your data", "No Buy/Sell signals", "Read-only broker connection roadmap", "Cloud security and account isolation before production sync"];

export function LandingPage() {
  return <div className="landing-page landing-grid">
    <header className="landing-header"><TradoviaLogo/><nav><a href="#product">Product</a><a href="#intelligence">Intelligence</a><a href="#pricing">Pricing</a></nav><div className="landing-actions"><button className="lang-button">EN / TH</button><Link className="link-button" href="/workspace">Open Workspace</Link></div></header>
    <main>
      <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">TRADING INTELLIGENCE PLATFORM</p><h1>Know your trading.<br/><span>Build your edge.</span></h1><p>Turn your trades into data, patterns and insights you can actually review. Tradovia is built to help traders understand their own performance and improve their process over time.</p><div className="hero-actions"><Link className="cta-primary" href="/workspace">Start with Tradovia</Link><a className="cta-secondary" href="#product">Explore the platform</a></div><small>Thailand first · Web first · Mobile-ready · No Buy/Sell signals</small></div><Card className="product-preview glow"><div className="preview-top"><span>Performance Overview</span><span className="data-state">Illustrative preview</span></div><div className="preview-metrics"><div><span>Net P&L</span><strong>—</strong></div><div><span>Win Rate</span><strong>—</strong></div><div><span>Realized R</span><strong>—</strong></div></div><div className="preview-chart"><div className="chart-line"/><span>Your real performance appears after you add or import trades.</span></div><div className="preview-insight"><span>TRADOVIA INTELLIGENCE</span><strong>Result → Why → Action</strong><p>Every insight is designed to trace back to your own trading data.</p></div></Card></section>
      <section className="workflow-strip" aria-label="Tradovia improvement loop">{workflow.map((item,index)=><div key={item}><strong>{item}</strong>{index<workflow.length-1&&<span>→</span>}</div>)}</section>
      <section id="product" className="landing-section"><div className="section-intro"><p className="eyebrow">ONE WORKSPACE</p><h2>From recording trades to understanding them.</h2><p>Keep the daily workflow simple while your accumulated trading data becomes more useful over time.</p></div><div className="product-grid">{productAreas.map(([title,copy],index)=><Card key={title} className="product-card"><span className="product-index">0{index+1}</span><h3>{title}</h3><p>{copy}</p></Card>)}</div></section>
      <section className="landing-section landing-showcase"><div className="showcase-copy"><p className="eyebrow">TRADING CALENDAR</p><h2>See the month you actually traded.</h2><p>Daily trade count and realized P&amp;L make review faster. Move between Day, Week, Month and Year, then open the underlying trades when something deserves attention.</p><Link className="cta-secondary" href="/workspace/calendar">Open Trading Calendar</Link></div><Card className="calendar-preview glow"><div className="calendar-preview-head"><span>September review</span><span>Day · Week · Month · Year</span></div><div className="calendar-preview-grid">{["1","2","3","4","5","8","9","10","11","12","15","16","17","18"].map((d,i)=><div key={d} className={i===3||i===9?"preview-loss":i===1||i===6||i===12?"preview-profit":""}><span>{d}</span>{i===1&&<strong>+$—</strong>}{i===3&&<strong>-$—</strong>}{i===6&&<small>2 trades</small>}</div>)}</div><small>Illustrative UI · not live market or account data</small></Card></section>
      <section id="intelligence" className="landing-section intelligence-section"><div><p className="eyebrow">TRADOVIA INTELLIGENCE</p><h2>Not more data.<br/>Better understanding.</h2><p>Performance becomes useful when every conclusion can lead back to the trades behind it.</p></div><Card className="intelligence-card"><div><span>RESULT</span><strong>What happened?</strong></div><div><span>WHY</span><strong>What patterns contributed?</strong></div><div><span>ACTION</span><strong>What should you review next?</strong></div><p>No Buy/Sell signals. Tradovia Intelligence is designed to help users understand their own recorded performance.</p></Card></section>
      <section className="landing-section"><div className="section-intro"><p className="eyebrow">TRADING ENVIRONMENT</p><h2>Journal, context and discipline in one workspace.</h2><p>Tools stay close to the review process without turning Tradovia into a crowded terminal.</p></div><div className="environment-grid">{environment.map(([title,copy])=><Card className="environment-card" key={title}><span>WORKSPACE</span><h3>{title}</h3><p>{copy}</p></Card>)}</div></section>
      <section className="landing-section roadmap-section"><div><p className="eyebrow">CONNECTED ACCOUNTS · ROADMAP</p><h2>Import first. Connect safely later.</h2><p>Tradovia starts with manual journaling and import workflows. MT5 connectivity is planned as read-only account synchronization—not trade execution.</p></div><Card className="roadmap-card"><span>Manual Journal</span><b>→</b><span>CSV / Statement Import</span><b>→</b><span>MT5 Read-only Sync</span><b>→</b><span>More Broker Connections</span></Card></section>
      <section className="landing-section trust-section"><div><p className="eyebrow">TRUST BY DESIGN</p><h2>Your trading history should never be ambiguous.</h2></div><div className="trust-grid">{trust.map(item=><div key={item}><span>✓</span><strong>{item}</strong></div>)}</div></section>
      <section id="pricing" className="landing-section"><div className="section-intro"><p className="eyebrow">PLANS</p><h2>Start simple. Upgrade when your workflow needs more.</h2></div><div className="pricing-grid"><Card className="price-card"><span>Starter</span><strong>Free</strong><p>Core manual journal, calendar and basic analytics.</p></Card><Card className="price-card featured"><span>Pro</span><strong>฿199 <small>/ month</small></strong><p>฿1,990/year · Unlimited journal, full analytics and Edge Intelligence · 7-day free trial.</p></Card><Card className="price-card"><span>Elite</span><strong>฿299 <small>/ month</small></strong><p>฿2,990/year · Connected-account and advanced intelligence roadmap.</p></Card></div></section>
    </main>
    <footer className="landing-footer"><TradoviaLogo compact/><span>Know your trading. Build your edge.</span><span>© Tradovia</span></footer>
  </div>;
}
